[build]
  publish = "/"
  
# Domain redirects - redirect www version to non-www
[[redirects]]
  from = "https://www.merritts-auto-recycling.com/*"
  to = "https://merritts-auto-recycling.com/:splat"
  status = 301

# Also handle non-HTTPS www version
[[redirects]]
  from = "http://www.merritts-auto-recycling.com/*"
  to = "https://merritts-auto-recycling.com/:splat"
  status = 301

# Force HTTPS for the canonical domain (only for non-HTTPS requests)
[[redirects]]
  from = "http://merritts-auto-recycling.com/*"
  to = "https://merritts-auto-recycling.com/:splat"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 